version : '3.8'
services:
  prometheus:
    image: bitnami/prometheus:2.51.2
    container_name: prometheus
    ports:
     - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
     - "3000:3000"
    restart: unless-stopped
    volumes:
     - ./src/main/resources/grafana/datasources:/etc/grafana/provisioning/datasources